config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'reset_password/new'

  get 'reset_password/edit'

  root 'main_pages#home'
  get 'help'      => 'main_pages#help'
  get 'about'     => 'main_pages#about'
  get 'contact'   => 'main_pages#contact'
  get 'terms'     => 'main_pages#terms'
  get 'privacy'   => 'main_pages#privacy'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Skaxis - created by Joseph Kim.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About Me", about_path %></li>
      <li><%= link_to "Contact",  contact_path %></li>
      <li><%= link_to "Terms",    terms_path %></li>
      <li><%= link_to "Privacy",  privacy_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Skaxis", root_path, id: "logo" %></li>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>